name: centauri-ocr-env
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - argon2-cffi-bindings=21.2.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=4.1.0
  - ca-certificates=2021.5.30
  - cffi=1.14.6
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - importlib-metadata=4.8.1
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jsonschema=3.2.0
  - jupyter_client=7.0.3
  - jupyterlab_pygments=0.1.2
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - nbclient=0.5.4
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - openssl=1.1.1l
  - pandoc=2.14.2
  - pandocfilters=1.5.0
  - parso=0.8.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.1.1
  - prompt-toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.10.0
  - pyodbc=4.0.30
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pytesseract=0.3.13
  - python=3.8.10
  - python_abi=3.8
  - pyzmq=22.3.0
  - readline=8.1
  - send2trash=1.8.0
  - six=1.16.0
  - sqlite=3.35.4
  - terminado=0.12.1
  - testpath=0.5.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.1.0
  - unixodbc=2.3.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - pip:
    - aiohttp==3.9.0
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - aiosignal==1.3.1
    - argon2-cffi==21.1.0
    - async-timeout==4.0.3
    - blessings==1.7
    - cachetools==4.2.2
    - certifi==2023.7.22
    - chardet==4.0.0
    - click==8.0.1
    - colorama==0.4.4
    - colorful==0.5.4
    - debugpy==1.4.3
    - filelock==3.0.12
    - frozenlist==1.4.1
    - google-api-core==1.28.0
    - google-auth==1.30.1
    - googleapis-common-protos==1.53.0
    # - gpustat==0.6.0
    - greenlet==1.1.0
    - grpcio==1.62.0
    - hiredis==2.0.0
    - idna==2.10
    - ipykernel==6.4.1
    - jinja2==3.0.1
    - markupsafe==2.0.1
    - msgpack==1.0.2
    - multidict==5.1.0
    - numpy==1.20.3
    # - nvidia-ml-py3==7.352.0
    - opencensus==0.7.13
    - opencensus-context==0.1.2
    - opencv-python==4.5.2.52
    - packaging==20.9
    - pandas==1.2.4
    - azure-servicebus==7.12.2
    - azure-identity==1.17.1
    - pillow==10.2.0
    - prometheus-client==0.10.1
    - protobuf==3.18.3
    - py-spy==0.3.7
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    # - pytesseract==0.3.7
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pyyaml==5.4.1
    - ray==2.9.2
    - redis==3.5.3
    - requests==2.25.1
    - rsa==4.7.2
    - setuptools==65.5.1
    - sqlalchemy==1.4.15
    - typing_extensions==4.12.2
    - urllib3==1.26.5
    - wheel==0.38.1
    - yarl==1.6.3
