name: centauri-ocr-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - opencv
  - pytesseract  # Python bindings for Tesseract
  - pip
  - pip:
    - annotated-types==0.7.0
    - anyio==4.4.0
    - azure-core==1.30.2
    - azure-identity==1.17.1
    - azure-servicebus==7.12.2
    - certifi==2024.7.4
    - cffi==1.17.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cryptography==43.0.0
    - fastapi==0.112.0
    - h11==0.14.0
    - httptools==0.6.1
    - idna==3.7
    - isodate==0.6.1
    - msal==1.30.0
    - msal-extensions==1.2.0
    - portalocker==2.10.1
    - pycparser==2.22
    - pydantic==2.8.2
    - pydantic_core==2.20.1
    - PyJWT==2.9.0
    - python-dotenv==1.0.1
    - PyYAML==6.0.2
    - requests==2.32.3
    - six==1.16.0
    - sniffio==1.3.1
    - starlette==0.37.2
    - typing_extensions==4.12.2
    - urllib3==2.2.2
    - uvicorn==0.30.5
    - uvloop==0.19.0
    - watchfiles==0.23.0
    - websockets==12.0
